options:
  platform:     psx
  basename:     main
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/SLUS_005.61
  asm_path:     asm/us/main
  asset_path:   assets/main
  src_path:     src/main
  ld_script_path: main.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.main.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.main.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.main.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    - ".bss"
segments:
  - [0x800, header]
  - name: main
    type: code
    start: 0x00000800
    vram:  0x80010000
    align: 1
    subalign: 1
    subsegments:
      - [0x800, rodata]
      - [0x2824, asm]
      - [0x323C, c]
      - [0xC594C, asm]
      - [0xDEC0C, data]
  - [0x120000]
