options:
  asm_jtbl_label_macro: jlabel
  asm_path: asm/us/main
  asset_path: assets/main
  base_path: ..
  basename: main
  build_path: build/us
  compiler: GCC
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  ld_script_path: main.ld
  migrate_rodata_to_functions: false
  platform: psx
  section_order:
  - .rodata
  - .text
  - .data
  - .bss
  src_path: src/main
  symbol_addrs_path:
  - config/symbols.us.txt
  - config/symbols.us.main.txt
  target_path: disks/us/SLUS_005.61
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.main.txt
  undefined_syms_auto_path: config/undefined_syms_auto.us.main.txt
  use_legacy_include_asm: false
segments:
- - 2048
  - header
- align: 4
  name: main
  start: 2048
  subalign: 4
  subsegments:
  - - 2048
    - bin
  type: code
  vram: 2147549184
- align: 1
  name: main2
  start: 12860
  subalign: 1
  subsegments:
  - - 12860
    - c
  type: code
  vram: 2147559996
- align: 1
  name: main3
  start: 584924
  subalign: 1
  subsegments:
  - - 584924
    - bin
  type: code
  vram: 2148136156
- - 1179648
