options:
  platform:     psx
  basename:     main
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/SLUS_005.61
  asm_path:     asm/us/main
  asset_path:   assets/main
  src_path:     src/main
  ld_script_path: main.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.main.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.main.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.main.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  disassemble_all: true
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    - ".bss"
segments:
  - [0x800, header]
  - name: main
    type: code
    start: 0x00000800
    vram:  0x80010000
    align: 1
    subalign: 1
    subsegments:
      - [0x800, rodata]
      - [0xA44, .rodata, 323C]
      - [0xAC0, rodata]
      - [0x1C30, .rodata, select_a_character] # jtbl_80011430, func_800CCEF0
      - [0x1C68, .rodata, select_a_character] # jtbl_80011468, func_800CCF70
      - [0x1C9C, rodata]
      - [0x2824, c]
      - [0x323C, c]
      - [0xBD234, c, select_a_character]
      - [0xBDF8C, c]
      - [0xC594C, c]
      - [0xCB68C, asm] # doesn't seem like a function
      - [0xCB734, asm]
      - [0xCB748, asm, psxsdk/libspu/s_crwa]
      - [0xCC490, asm, psxsdk/libspu/s_ini]
      - [0xCC604, asm, psxsdk/libspu/s_dcb]
      - [0xCC628, asm, psxsdk/libspu/s_m_util]
      - [0xCC734, asm, psxsdk/libspu/s_gks]
      - [0xCC7C8, asm, psxsdk/libspu/s_stm]
      - [0xCCF20, asm, psxsdk/libsnd/sssnc]
      - [0xCD02C, asm, psxsdk/libsnd/ssinit]
      - [0xCD114, asm, psxsdk/libsnd/ssinit_c]
      - [0xCD144, asm, psxsdk/libspu/s_i]
      - [0xCD1F4, asm, psxsdk/libsnd/ssopenpj]
      - [0xCD6D0, asm, psxsdk/libsnd/ssplay]
      - [0xCD760, asm, psxsdk/libspu/s_q]
      - [0xCD8DC, asm, psxsdk/libsnd/sssattr]
      - [0xCD970, asm, psxsdk/libspu/s_sca]
      - [0xCDD04, asm, psxsdk/libsnd/sssmv]
      - [0xCDD54, asm, psxsdk/libsnd/ssstart]
      - [0xCDFBC, asm, psxsdk/libsnd/ut_ron]
      - [0xCE924, asm, psxsdk/libsnd/play]
      - [0xCF234, asm, psxsdk/libsnd/sssv]
      - [0xCF510, asm, psxsdk/libsnd/sstick]
      - [0xCF928, asm, psxsdk/libsnd/dmyprint]
      - [0xD02C0, asm, psxsdk/libsnd/ut_gva]
      - [0xD04FC, asm, psxsdk/libsnd/ut_keyv]
      - [0xD0908, asm, psxsdk/libsnd/ut_rdep]
      - [0xD09A0, asm, psxsdk/libspu/s_srmp]
      - [0xD1368, asm, psxsdk/libsnd/ut_rev]
      - [0xD141C, asm, psxsdk/libspu/s_sr]
      - [0xD1708, asm, psxsdk/libsnd/vm_aloc2]
      - [0xD191C, asm, psxsdk/libsnd/vm_f]
      - [0xD1CD0, asm, psxsdk/libspu/s_snv]
      - [0xD1CF4, asm, psxsdk/libspu/s_sav]
      - [0xD1EFC, asm, psxsdk/libsnd/vm_init]
      - [0xD220C, asm, psxsdk/libspu/s_m_init]
      - [0xD2260, asm, psxsdk/libspu/s_it]
      - [0xD3360, asm, psxsdk/libsnd/vm_noff]
      - [0xD33A4, asm, psxsdk/libsnd/vm_nowof]
      - [0xD4040, asm, psxsdk/libsnd/vm_stav]
      - [0xD4678, asm, psxsdk/libsnd/vm_vsu]
      - [0xD473C, asm, psxsdk/libsnd/vs_mono]
      - [0xD4760, asm, psxsdk/libsnd/vs_vab]
      - [0xD47E4, asm, psxsdk/libspu/s_m_f]
      - [0xD4B68, asm, psxsdk/libsnd/vs_vh]
      - [0xD529C, asm, psxsdk/libsnd/vs_vtbp]
      - [0xD53FC, asm, psxsdk/libspu/s_stsa]
      - [0xD5454, asm, psxsdk/libspu/s_wp]
      - [0xD54E0, asm, psxsdk/libsnd/vs_vtc]
      - [0xD55B0, asm, psxsdk/libetc/vsync]
      - [0xD5794, asm, psxsdk/libetc/intr]
      - [0xD5EA4, asm, psxsdk/libetc/intr_vb]
      - [0xD5FCC, asm, psxsdk/libetc/intr_dma]
      - [0xD6274, asm, psxsdk/libetc/vmode]
      - [0xD628C, asm, psxsdk/libgs/gs_125]
      - [0xD8134, asm, psxsdk/libgs/gs_101]
      - [0xD881C, asm, psxsdk/libcd/cdread2]
      - [0xD88D0, asm, psxsdk/libcd/c_002]
      - [0xD8A78, asm, psxsdk/libcd/c_005]
      - [0xD8B00, asm, psxsdk/libcd/c_007]
      - [0xD8BB8, asm, psxsdk/libcd/c_008]
      - [0xD8BF4, asm, psxsdk/libcd/c_009]
      - [0xD8CB8, asm, psxsdk/libcd/c_010]
      - [0xD8CD8, asm, psxsdk/libcd/c_011]
      - [0xD9838, asm] # linker junk?
      - [0xD9840, asm]
      - [0xDDD40, asm] # unknown
      - [0xDDD74, asm]
      - [0xDE0D8, asm, psxsdk/libcard/c112]
      - [0xDE0E8, asm, psxsdk/libcard/c171]
      - [0xDE0F8, asm, psxsdk/libcard/c172]
      - [0xDE108, asm, psxsdk/libcard/card]
      - [0xDE140, asm, psxsdk/libcard/a78]
      - [0xDE150, asm, psxsdk/libcard/a80]
      - [0xDE21C, asm, psxsdk/libcard/a74]
      - [0xDE22C, asm, psxsdk/libcard/a75]
      - [0xDE23C, asm, psxsdk/libcard/a76]
      - [0xDE46C, asm] # unknown
      - [0xDE48C, asm, psxsdk/libc/c19]
      - [0xDE49C, asm, psxsdk/libc/c25]
      - [0xDE4AC, asm, psxsdk/libc/c42]
      - [0xDE4BC, asm, psxsdk/libc/c43]
      - [0xDE4CC, asm, psxsdk/libc/c63]
      - [0xDE4DC, asm, psxsdk/libapi/c57]
      - [0xDE4EC, asm, psxsdk/libapi/c68]
      - [0xDE4FC, asm, psxsdk/libapi/c73]
      - [0xDE52C, asm, psxsdk/libapi/a07]
      - [0xDE53C, asm, psxsdk/libapi/a08]
      - [0xDE54C, asm, psxsdk/libapi/a09]
      - [0xDE55C, asm, psxsdk/libapi/a10]
      - [0xDE56C, asm, psxsdk/libapi/a11]
      - [0xDE57C, asm, psxsdk/libapi/a12]
      - [0xDE58C, asm, psxsdk/libapi/a13]
      - [0xDE59C, asm, psxsdk/libapi/a14]
      - [0xDE5AC, asm, psxsdk/libapi/a15]
      - [0xDE5BC, asm, psxsdk/libapi/a16]
      - [0xDE5CC, asm, psxsdk/libapi/a23]
      - [0xDE5DC, asm, psxsdk/libapi/a24]
      - [0xDE5EC, asm, psxsdk/libapi/a25]
      - [0xDE5FC, asm, psxsdk/libapi/a36]
      - [0xDE60C, asm, psxsdk/libapi/a37]
      - [0xDE61C, asm, psxsdk/libapi/a50]
      - [0xDE62C, asm, psxsdk/libapi/a52]
      - [0xDE63C, asm, psxsdk/libapi/a53]
      - [0xDE64C, asm, psxsdk/libapi/a54]
      - [0xDE65C, asm, psxsdk/libapi/a65]
      - [0xDE66C, asm, psxsdk/libapi/a66]
      - [0xDE67C, asm, psxsdk/libapi/a67]
      - [0xDE68C, asm, psxsdk/libapi/a91]
      - [0xDE69C, asm, psxsdk/libapi/l10]
      - [0xDE6AC, asm, psxsdk/libapi/counter]
      - [0xDEB1C, asm, psxsdk/libapi/a18]
      - [0xDEB2C, asm, psxsdk/libapi/a19]
      - [0xDEB3C, asm, psxsdk/libapi/a20]
      - [0xDEB4C, asm, psxsdk/libapi/a21]
      - [0xDEB5C, asm, psxsdk/libapi/l02]
      - [0xDEB6C, asm, psxsdk/libapi/l03]
      - [0xDEC0C, data]
  - [0x120000]
