#include "common.h"

#define XA(sequence_, volume_) \
    {                          \
        sequence_, volume_     \
    }

struct XaSequenceData D_800F1A0C = {
    {
        { { XA(MUSIC_STAGE_INTRO_X, 0x75), XA(MUSIC_STAGE_INTRO_ZERO, 0x70) }, { XA(MUSIC_STAGE_INTRO_X, 0x75), XA(MUSIC_STAGE_INTRO_ZERO, 0x70) } },
        { { XA(MUSIC_STAGE_JUNGLE, 0x7F), XA(MUSIC_STAGE_JUNGLE, 0x7F) }, { XA(MUSIC_STAGE_JUNGLE, 0x7F), XA(MUSIC_STAGE_JUNGLE, 0x7F) } },
        { { XA(MUSIC_STAGE_SNOW_BASE, 0x7F), XA(MUSIC_STAGE_SNOW_BASE, 0x7F) }, { XA(MUSIC_STAGE_SNOW_BASE_2, 0x7F), XA(MUSIC_STAGE_SNOW_BASE_2, 0x7F) } },
        { { XA(MUSIC_STAGE_BIO_LABORATORY, 0x75), XA(MUSIC_STAGE_BIO_LABORATORY, 0x75) }, { XA(MUSIC_STAGE_BIO_LABORATORY, 0x75), XA(MUSIC_STAGE_BIO_LABORATORY, 0x75) } },
        { { XA(MUSIC_STAGE_VOLCANO, 0x78), XA(MUSIC_STAGE_VOLCANO, 0x78) }, { XA(MUSIC_STAGE_VOLCANO, 0x78), XA(MUSIC_STAGE_VOLCANO, 0x78) } },
        { { XA(MUSIC_STAGE_MARINE_BASE, 0x75), XA(MUSIC_STAGE_MARINE_BASE, 0x75) }, { XA(MUSIC_STAGE_MARINE_BASE, 0x75), XA(MUSIC_STAGE_MARINE_BASE, 0x75) } },
        { { XA(MUSIC_STAGE_CYBER_SPACE, 0x7F), XA(MUSIC_STAGE_CYBER_SPACE, 0x7F) }, { XA(MUSIC_STAGE_CYBER_SPACE, 0x7F), XA(MUSIC_STAGE_CYBER_SPACE, 0x7F) } },
        { { XA(MUSIC_STAGE_AIR_FORCE, 0x7F), XA(MUSIC_STAGE_AIR_FORCE, 0x7F) }, { XA(MUSIC_STAGE_AIR_FORCE, 0x7F), XA(MUSIC_STAGE_AIR_FORCE, 0x7F) } },
        { { XA(MUSIC_STAGE_MILITARY_TRAIN, 0x7F), XA(MUSIC_STAGE_MILITARY_TRAIN, 0x7F) }, { XA(MUSIC_STAGE_MILITARY_TRAIN, 0x7F), XA(MUSIC_STAGE_MILITARY_TRAIN, 0x7F) } },
        { { XA(MUSIC_STAGE_JUNGLE, 0x00), XA(MUSIC_STAGE_JUNGLE, 0x00) }, { XA(MUSIC_STAGE_JUNGLE, 0x00), XA(MUSIC_STAGE_JUNGLE, 0x00) } },
        { { XA(MUSIC_STAGE_SPACE_PORT, 0x7F), XA(MUSIC_STAGE_SPACE_PORT, 0x7F) }, { XA(MUSIC_STAGE_SPACE_PORT, 0x7F), XA(MUSIC_STAGE_SPACE_PORT, 0x7F) } },
        { { XA(MUSIC_STAGE_FINAL_WEAPON, 0x7F), XA(MUSIC_STAGE_FINAL_WEAPON, 0x7F) }, { XA(MUSIC_STAGE_FINAL_WEAPON, 0x7F), XA(MUSIC_STAGE_FINAL_WEAPON, 0x7F) } },
        { { XA(MUSIC_STAGE_FINAL_WEAPON, 0x7F), XA(MUSIC_STAGE_FINAL_WEAPON, 0x7F) }, { XA(MUSIC_STAGE_FINAL_WEAPON, 0x7F), XA(MUSIC_STAGE_FINAL_WEAPON, 0x7F) } },
        { { XA(MUSIC_STAGE_JUNGLE, 0x7F), XA(MUSIC_STAGE_JUNGLE, 0x7F) }, { XA(MUSIC_STAGE_JUNGLE, 0x7F), XA(MUSIC_STAGE_JUNGLE, 0x7F) } },
        { { XA(MUSIC_STAGE_JUNGLE, 0x7F), XA(MUSIC_STAGE_JUNGLE, 0x7F) }, { XA(MUSIC_STAGE_JUNGLE, 0x7F), XA(MUSIC_STAGE_JUNGLE, 0x7F) } },
        { { XA(MUSIC_STAGE_JUNGLE, 0x7F), XA(MUSIC_STAGE_JUNGLE, 0x7F) }, { XA(MUSIC_STAGE_JUNGLE, 0x7F), XA(MUSIC_STAGE_JUNGLE, 0x7F) } },
    },
    {
        XA(MUSIC_INTRO_BOSS_BATTLE, 0x70),
        XA(MUSIC_BOSS_BATTLE, 0x70),
        XA(MUSIC_BOSS_BATTLE, 0x70),
        XA(MUSIC_BOSS_BATTLE, 0x70),
        XA(MUSIC_BOSS_BATTLE, 0x70),
        XA(MUSIC_BOSS_BATTLE, 0x70),
        XA(MUSIC_BOSS_BATTLE, 0x70),
        XA(MUSIC_BOSS_BATTLE, 0x70),
        XA(MUSIC_BOSS_BATTLE, 0x70),
        XA(MUSIC_REPLIFORCE_BATTLE, 0x7F),
        XA(MUSIC_REPLIFORCE_BATTLE, 0x7F),
        XA(MUSIC_REPLIFORCE_BATTLE, 0x7F),
        XA(MUSIC_STAGE_SPACE_PORT, 0x7F),
        XA(MUSIC_STAGE_FINAL_WEAPON, 0x75),
        XA(MUSIC_BOSS_BATTLE, 0x70),
        XA(MUSIC_BOSS_BATTLE, 0x70),
    },
};

s32 D_800F1AAC = 1;

void (*D_800F1AB0[])(void) = {
    func_80016B38,
    func_80016B58,
    func_80016BDC,
    func_80016C5C,
    func_80016D0C,
    func_80016DAC,
    func_80016E34,
    func_80016E84,
};
