#ifndef MMX4_GAME_PROTOTYPES_H
#define MMX4_GAME_PROTOTYPES_H

extern s32 func_80013614 (s32 arg0, s32 *arg1);
extern s32 func_800169D8 (void);
extern s32 func_8001CEDC (void);
extern s32 func_8001CFF4(s32 arg0);
extern s32 func_8001CF74 (void);
extern u8 func_8001E850 (u8 *arg0, u8 arg1);
extern void func_8001E980 (u8 arg0);
extern s32 func_8001FD7C (struct EngineObj *arg0);
extern s32 func_8002D1F8 (struct PlayerObj *arg0, u8 arg1, s32 arg2);
extern s32 func_8002D25C (struct PlayerObj *arg0);
extern s32 func_8002D41C (struct PlayerObj *arg0, s32 arg1, s32 arg2);
extern s32 func_8002D6BC (struct PlayerObj *arg0, u8 arg1);
extern s32 player_check_dash_jump (struct PlayerObj *arg0);
extern s32 player_check_walk_start (struct PlayerObj *arg0);
extern s32 player_dash_should_end (struct PlayerObj *arg0);
extern s32 player_check_ladder (struct PlayerObj *arg0);
extern s32 player_check_dash_jump_walk (struct PlayerObj *arg0);
extern s32 player_check_script (struct PlayerObj *arg0);
extern s32 player_leap_check_peak (struct PlayerObj *arg0);
extern u16 player_map_buttons (s32 arg0);
extern s32 player_check_shoot (struct PlayerObj *arg0);
extern s32 player_check_nova_strike (struct PlayerObj *arg0);
extern s32 player_set_charge_flash (struct PlayerObj *arg0, s8 arg1);
extern s32 player_charge_released (struct PlayerObj *arg0);
extern s32 player_nova_strike_hit_wall (struct PlayerObj *arg0);
extern s32 player_zero_check_ground_technique (struct PlayerObj *arg0);
extern s32 player_zero_check_saber (struct PlayerObj *arg0);
extern s32 player_zero_check_fall_slash (struct PlayerObj *arg0);
extern s32 player_zero_check_slash_input (struct PlayerObj *arg0);
extern struct EffectObj *find_free_effect_obj (void);
extern struct ItemObj *find_free_item_obj (void);
extern struct LayerObj *find_free_layer_obj (void);
extern struct MiscObj *find_free_misc_obj (void);
extern struct MiscObj *func_8002AE90 (struct MiscObj *arg0, s32 arg1);
extern struct QuadObj *find_free_quad_obj (void);
extern struct QuadObj *func_8001DC7C (s8 arg0, s8 arg1);
extern struct ShotObj *find_free_shot_obj (void);
extern struct MainObj *find_free_main_obj (void);
extern struct UnkObj *find_free_unk_obj (void);
extern struct VisualObj *find_free_visual_obj (void);
extern struct VisualObj *func_8002AF4C (struct VisualObj *arg0, s32 arg1);
extern struct WeaponObj *find_free_weapon_obj (void);
extern u8 func_8001385C (void);
extern u8 angle_from_delta (s32 arg0, s32 arg1);
extern u8 func_8002D8B8 (struct PlayerObj *arg0);
extern u8 func_8002D94C (struct PlayerObj *arg0);
extern u8 get_random ();
extern void CollisionRelated (struct PlayerObj *arg0);
extern void InitMemcards (void);
extern void MegamanInBriefingRoomUpdate (struct MiscObj *arg0);
extern void MegamanRelatedUpdate (struct MiscObj *arg0);
extern void PlayCapcomLogo (void);
extern void SearchLightUpdate (struct QuadObj *arg0);
extern void SelectACharacterUpdate (struct MiscObj *arg0);
extern void Set24BitDisp (s32 w, s32 h);
extern void TitleLogoUpdate (struct MiscObj *arg0);
extern void TitleScalingXUpdate (struct EffectObj *arg0);
extern void TitleSetWhiteQuadSpeed (struct QuadObj *arg0);
extern void TitleUpdate (struct MiscObj *arg0);
extern void TitleUpdate2 (struct QuadObj *arg0);
extern void character_select_spawn_objects (struct EngineObj *arg0);
extern void character_select_state_0 (struct EngineObj *arg0);
extern void character_select_state_1 (struct EngineObj *arg0);
extern void character_select_state_2 (struct EngineObj *arg0);
extern void character_select_state_2_substate_0 (struct EngineObj *arg0);
extern void character_select_state_3 (struct EngineObj *arg0);
extern void character_select_state_4 (struct EngineObj *arg0);
extern void character_select_state_5 (struct EngineObj *arg0);
extern void character_select_state_6 (struct EngineObj *arg0);
extern void clear_vram_rect_ptrs (void);
extern void decompress_gfx (u16 *src, u16 *dest);
extern void decompress_player_gfx (struct GraphicsObj *arg0, s16 x, s16 y);
extern void dmy_nothing1 (short int arg0, short int arg1, unsigned char arg2, unsigned char arg3);
extern void engine_state_0 (struct EngineObj *arg0);
extern void engine_state_1 (struct EngineObj *arg0);
extern void engine_state_2 (struct EngineObj *arg0);
extern void engine_state_3 (struct EngineObj *arg0);
extern void engine_state_4 (struct EngineObj *arg0);
extern void engine_state_6 (struct EngineObj *arg0);
extern void func_80012024 (void);
extern void func_80012454 (void);
extern void func_80012560 (void);
extern void func_80012600 (void);
extern void func_80012740 (s32 arg0, void *arg1);
extern void func_80012854 (s32 arg0);
extern void func_800128B8 (void (*arg0) (void));
extern void func_800128EC (s32 arg0);
extern void func_80012910 (s32 arg0);
extern void func_80012934 (s32 arg0);
extern void func_80012944 (void);
extern void func_80012E38 (void);
extern void func_80012E80 (void);
extern void func_80012EB0 (void);
extern void func_8001326C (u8 arg0);
extern void func_80013404 (u8 arg0);
extern void func_80013588 ();
extern void func_80013968 (void);
extern void func_80013DA8 (void);
extern void func_80014140 (void);
extern void func_800142BC (void);
extern void func_80014514 (void);
extern void func_80014780 (void);
extern void func_800147AC (void);
extern void func_800148E4 (void);
extern void func_800148EC (void);
extern void func_80014968 (void);
extern void func_80014DC4 (void);
extern void func_8001512C (void);
extern void func_80015C10 (void);
extern void func_80016074 (void);
extern void func_800160AC (void);
extern void func_800160F4 (void);
extern void func_80016420 (s8 arg0);
extern void func_80016448 (u8 arg0);
extern void func_800164D8 (void);
extern void func_800168D8 (void);
extern void func_80016B38 (void);
extern void func_80016B58 (void);
extern void func_80016BDC (void);
extern void func_80016DAC (void);
extern void func_80016E34 (void);
extern void func_80016E84 (void);
extern void func_800170E0 (void);
extern void func_80017340(void);
extern void func_80018AD0 (s32 arg0, s32 arg1, s32 arg2, s32 arg3, s32 arg4, s32 arg5, s32 arg6, s32 arg7, s32 arg8, s32 arg9);
extern void func_80018E50 (void);
extern void func_80018EEC (void);
extern void func_80018FD0 (u32 arg0);
extern void func_80019058 (s8 arg0);
extern void func_800190F0 (s32 arg0);
extern void func_80019100 (void);
extern void func_80019208 (void);
extern void func_80019228 (void);
extern void func_800192F8 (void);
extern void func_800193D8 (struct EngineObj *arg0);
extern void func_80019B64 (struct EngineObj *arg0);
extern void func_8001A8E8 (struct EngineObj *arg0);
extern void func_8001B558 (struct EngineObj *arg0);
extern void func_8001D104 (void);
extern void func_8001D178 (struct GameInfo *arg0);
extern void func_8001D1A4 (struct GameInfo *arg0);
extern void func_8001D1F0 (struct GameInfo *arg0);
extern void func_8001D284 (struct GameInfo *arg0);
extern void func_8001D294 (struct GameInfo *arg0);
extern void func_8001D2D0 (struct GameInfo *arg0);
extern void func_8001D364 (struct GameInfo *arg0);
extern void func_8001D460 (struct GameInfo *arg0);
extern void func_8001D514 (struct GameInfo *arg0);
extern void func_8001D57C (struct GameInfo *arg0);
extern void func_8001D5C8 (struct GameInfo *arg0);
extern void func_8001D64C (struct GameInfo *arg0);
extern void func_8001D698 (struct GameInfo *arg0);
extern void func_8001D6DC (struct GameInfo *arg0);
extern void func_8001D77C (struct GameInfo *arg0);
extern void func_8001D7D0 (struct GameInfo *arg0);
extern void func_8001D8DC (struct GameInfo *arg0);
extern void func_8001D9D0 (struct GameInfo *arg0);
extern void func_8001DA70 (void);
extern void func_8001DAA0 (void);
extern void func_8001DAD0 (struct GameInfo *arg0);
extern void func_8001DCCC (struct GameInfo *arg0);
extern void func_8001DDB0 (struct GameInfo *arg0);
extern void func_8001DE20 (struct GameInfo *arg0);
extern void func_8001DE54 (struct GameInfo *arg0);
extern void func_8001DF48 (struct GameInfo *arg0);
extern void func_8001DF7C (struct GameInfo *arg0);
extern void func_8001E000 (struct GameInfo *arg0);
extern void func_8001E3FC (struct GameInfo *arg0);
extern void func_8001E458 (struct GameInfo *arg0);
extern void func_8001E4F0 (struct GameInfo *arg0);
extern void func_8001E54C (struct GameInfo *arg0);
extern void func_8001E638 (struct GameInfo *arg0);
extern void func_8001E690 (struct GameInfo *arg0);
extern void func_8001E6BC (struct GameInfo *arg0);
extern void func_8001E708 (struct GameInfo *arg0);
extern void func_8001EC34 (struct GameInfo *arg0);
extern void func_8001F0BC (struct GameInfo *arg0);
extern void func_8001F118 (void);
extern void func_8001F398 (struct EngineObj *arg0);
extern void func_8001F9A0 (struct EngineObj *arg0);
extern void func_8001FAC0 (struct EngineObj *arg0);
extern void func_8001FAFC (struct EngineObj *arg0);
extern void func_8001FC20 (struct EngineObj *arg0);
extern void func_8001FDBC (void);
extern void func_8001FEC0 (void);
extern void func_8001FF8C (struct EngineObj *arg0);
extern void func_80020060 (struct EngineObj *arg0);
extern void func_80020368 (struct EngineObj *arg0);
extern void func_80020390 (struct EngineObj *arg0);
extern void func_8002044C (struct EngineObj *arg0);
extern void func_80020464 (struct EngineObj *arg0);
extern void func_800204A4 (void);
extern void func_800204AC (struct EngineObj *arg0);
extern void func_80020638 (struct EngineObj *arg0);
extern void func_800206D0 (struct EngineObj *arg0);
extern void func_80020808 (struct EngineObj *arg0);
extern void func_8002088C (struct EngineObj *arg0);
extern void func_80020984 (struct EngineObj *arg0);
extern void func_80020A08 (struct EngineObj *arg0);
extern void func_80020AC8 (struct EngineObj *arg0);
extern void func_80020B1C (struct EngineObj *arg0);
extern void func_80020B8C (struct EngineObj *arg0);
extern void func_80020C24 (struct EngineObj *arg0);
extern void func_80020CB8 (struct EngineObj *arg0);
extern void func_80020D3C (struct EngineObj *arg0);
extern void func_80020D98 (struct EngineObj *arg0);
extern void func_80020DEC (u8 *arg0, s16 arg1);
extern void func_80020ED4 (struct EngineObj *arg0);
extern void func_80020F24 (struct EngineObj *arg0);
extern void func_800210B8 (struct EngineObj *arg0);
extern void func_80021104 (struct EngineObj *arg0);
extern void func_80021158 (void);
extern void func_80021C14 (void);
extern void func_80021CC8 (void);
extern void func_80021D20 (void);
extern void func_80021D84 (void);
extern void func_80021E3C (void);
extern void func_80021E74 (void);
extern void func_80022074 (void);
extern void func_8002328C (struct AbcObj *arg0);
extern void func_80023624 (struct EngineObj *arg0);
extern void func_80023684 (struct EngineObj *arg0);
extern void func_80023698 (struct EngineObj *arg0);
extern void func_800237E4 (struct EngineObj *arg0);
extern void func_80023870 (struct EngineObj *arg0);
extern void func_800238F0 (struct EngineObj *arg0);
extern void func_800239E0 (struct EngineObj *arg0);
extern void func_80023A54 (struct EngineObj *arg0);
extern void func_80023CA4 (struct MiscObj *arg0);
extern void func_80023CE0 (void);
extern void func_80023D90 (void);
extern void func_800241E8 (void);
extern void func_80024E70 (void);
extern void func_80024F5C (struct PlayerObj *arg0);
extern void func_8002509C (struct PlayerObj *arg0);
extern void func_800257BC (struct PlayerObj *arg0);
extern void func_80025CDC (void);
extern void func_80025DA0 (s32 texture_depth, s32 blend_mode);
extern void func_80026118 (void);
extern void func_800264D0 (s32 layer, s32 x, s32 y);
extern void func_80026720 (void);
extern void func_800267D4 (s32 input);
extern void func_80026894 (s32 arg0);
extern void func_80026CEC (s32 arg0);
extern void func_8002728C (void);
extern void func_8002771C (void);
extern void func_80027850 (void);
extern void func_80027908 (struct BackgroundObj *arg0);
extern void func_80027974 (struct BackgroundObj *arg0);
extern void func_80027A5C (struct BackgroundObj *a0);
extern void func_80027D40 (void);
extern void func_80027DC0 (struct BackgroundObj *arg0);
extern void func_80028070 (struct BackgroundObj *arg0);
extern void func_80028138 (void);
extern void func_800281E8 (void);
extern void func_80028268 (struct BackgroundObj *arg0);
extern void func_80028390 (struct BackgroundObj *arg0);
extern void func_8002859C (struct BackgroundObj *arg0);
extern void func_800285E0 (struct BackgroundObj *arg0);
extern void func_80028BF0 (void);
extern void func_80028DB4 (void);
extern void func_80028F58 (void);
extern void func_80029DBC (void);
extern void func_80029E1C (struct GameInfo *arg0);
extern void func_8002A394 (struct GameInfo *arg0);
extern void func_8002A41C (struct GameInfo *arg0);
extern void despawn_object (struct ObjectHeader *arg0);
extern void despawn_object_permanently (struct ObjectHeader *arg0);
extern void func_8002B450 (void);
extern void func_8002B458 (struct QuadObj *arg0);
extern void func_8002B460 (void);
extern void move_with_gravity (struct AnimatedObj *arg0);
extern ret_s8 func_8002DD04 (struct MainObj *arg0);
extern void func_8002C760 (struct PlayerObj *arg0);
extern void func_8002C808 (struct PlayerObj *arg0);
extern void func_8002C954 (struct PlayerObj *arg0);
extern void func_8002C9E4 (struct PlayerObj *arg0);
extern void func_8002CDD4 (struct PlayerObj *arg0);
extern void collide_with_players (struct PlayerObj *arg0);
extern void func_8002E420 (struct EngineObj *arg0);
extern void func_8002E5E0 (void);
extern void func_8002E698 (struct EngineObj *arg0);
extern void func_8002E8D4 (struct EngineObj *arg0);
extern void func_8002ED80 (struct EngineObj *arg0);
extern void func_8002ED98 (struct EngineObj *arg0);
extern void func_8002EDD4 (struct EngineObj *arg0);
extern void func_8002EF14 (struct EngineObj *arg0);
extern void func_8002F1B4 (struct EngineObj *arg0);
extern void func_8002F264 (struct EngineObj *arg0);
extern void func_8002F2A0 (struct EngineObj *arg0);
extern void func_8002F47C (struct EngineObj *arg0);
extern void func_8002F4C4 (struct EngineObj *arg0);
extern void func_8002F510 (struct EngineObj *arg0);
extern void func_8002F524 (struct EngineObj *arg0);
extern void func_8002F584 (struct EngineObj *arg0);
extern void func_8002F5E8 (struct EngineObj *arg0);
extern void func_8002F698 (struct EngineObj *arg0);
extern void func_8002F6E4 (struct EngineObj *arg0);
extern void func_8002F7A8 (struct EngineObj *arg0);
extern void func_8002F828 (struct EngineObj *arg0);
extern void func_8002F87C (struct EngineObj *arg0);
extern void func_8002F8F8 (struct EngineObj *arg0);
extern void func_8002F92C (struct EngineObj *arg0);
extern void func_8002F9EC (struct EngineObj *arg0);
extern void func_8002FAB0 (struct EngineObj *arg0);
extern void func_8002FAE4 (struct EngineObj *arg0);
extern void func_8002FB54 (struct EngineObj *arg0);
extern void func_8002FBDC (struct EngineObj *arg0);
extern void func_8002FCAC (void);
extern void func_8002FCEC (struct BarObj *arg0);
extern void func_8002FD28 (struct BarObj *arg0);
extern void func_800300AC (struct BarObj *arg0);
extern void func_80030128 (struct BarObj *arg0);
extern void func_80030F9C (struct BarObj *arg0);
extern void func_80030FD8 (struct BarObj *arg0);
extern void func_80031014 (struct BarObj *arg0);
extern void func_80031130 (struct BarObj *arg0);
extern void player_update (void);
extern void player_update_normal (struct PlayerObj *arg0);
extern void player_beam_in (struct PlayerObj *arg0);
extern void player_idle (struct PlayerObj *arg0);
extern void player_dash (struct PlayerObj *arg0);
extern void player_air_dash (struct PlayerObj *arg0);
extern void player_ladder_transition (struct PlayerObj *arg0);
extern void player_hurt (struct PlayerObj *arg0);
extern void player_check_fall (struct PlayerObj *arg0);
extern void player_update_double_tap (struct PlayerObj *arg0);
extern void player_check_capsule (struct PlayerObj *arg0);
extern void player_check_ride (struct PlayerObj *arg0);
extern void player_check_damage (struct PlayerObj *arg0);
extern void player_reset_actions (struct PlayerObj *arg0);
extern void player_noop (void);
extern void player_enter_idle (struct PlayerObj *arg0);
extern void player_zero_saber_on_event (struct PlayerObj *arg0, s8 arg1);
extern void player_zero_spawn_saber (struct PlayerObj *arg0, s8 arg1);
extern void player_enter_stand (struct PlayerObj *arg0);
extern void player_enter_walk (struct PlayerObj *arg0);
extern void player_enter_fall (struct PlayerObj *arg0);
extern void player_enter_air_dash_end (struct PlayerObj *arg0);
extern void func_800349F4 (struct PlayerObj *arg0);
extern void player_enter_ladder_down (struct PlayerObj *arg0);
extern void player_spawn (void);
extern void player_init_clone (void);
extern void player_update_init (struct PlayerObj *arg0);
extern void player_entry_beam_in (struct PlayerObj *arg0);
extern void player_entry_ride (struct PlayerObj *arg0);
extern void player_update_death (struct PlayerObj *arg0);
extern void player_update_inactive (struct PlayerObj *arg0);
extern void player_update_frame_hitbox (struct PlayerObj *arg0);
extern void player_set_collision_bounds (struct PlayerObj *arg0);
extern void player_read_input (void);
extern void player_clear_attack (struct PlayerObj *arg0);
extern void player_clear_flash (struct PlayerObj *arg0);
extern void player_update_flash (struct PlayerObj *arg0);
extern void player_copy_palette (struct PlayerObj *arg0, s32 arg1, s32 arg2);
extern void player_reset_palette (struct PlayerObj *arg0);
extern void player_set_palette (struct PlayerObj *arg0, s32 arg1);
extern void player_set_idle_animation (struct PlayerObj *arg0);
extern void player_air_steer (struct PlayerObj *arg0);
extern void player_spawn_dash_dust (struct PlayerObj *arg0);
extern void player_spawn_wall_kick_spark (struct PlayerObj *arg0);
extern void player_start_script_action (s8 arg0, s8 arg1);
extern void player_end_script_action (void);
extern void player_check_splash (struct PlayerObj *arg0);
extern void func_80036BF4 (struct PlayerObj *arg0, s16 arg1);
extern struct VisualObj *player_spawn_visual (s8 arg0, s8 arg1, s8 arg2, void *arg3);
extern void player_update_weapon (struct PlayerObj *arg0);
extern void player_update_shot_types (struct PlayerObj *arg0);
extern void player_update_charged_shot_type (struct PlayerObj *arg0, s32 arg1);
extern void player_equip_weapon (struct PlayerObj *arg0);
extern void player_update_shooting (struct PlayerObj *arg0);
extern void player_check_shoot_button (struct PlayerObj *arg0);
extern void player_check_special_button (struct PlayerObj *arg0);
extern void player_use_weapon_energy (struct PlayerObj *arg0, s8 arg1);
extern void player_fire_none (struct PlayerObj *arg0);
extern void player_update_charge (struct PlayerObj *arg0);
extern void player_charge_shoot_button (struct PlayerObj *arg0);
extern void player_charge_special_button (struct PlayerObj *arg0);
extern void player_reset_charge_and_weapon (struct PlayerObj *arg0);
extern void player_reset_charge (struct PlayerObj *arg0);
extern void player_set_animation_shooting (struct PlayerObj *arg0, s32 arg1);
extern void func_80038568 (struct PlayerObj *arg0, s32 arg1);
extern void player_idle_animate (struct PlayerObj *arg0);
extern void player_enter_ladder_shoot (struct PlayerObj *arg0);
extern void player_set_ladder_shoot_animation (struct PlayerObj *arg0);
extern void player_hover (struct PlayerObj *arg0);
extern void player_nova_strike (struct PlayerObj *arg0);
extern void player_rising_fire_charged (struct PlayerObj *arg0);
extern void player_rising_fire_charged_rise (struct PlayerObj *arg0);
extern void player_rising_fire_charged_peak (struct PlayerObj *arg0);
extern void player_zero_begin_attack (struct PlayerObj *arg0);
extern s32 func_8003A1DC (struct PlayerObj *arg0);
extern s32 player_zero_check_ladder_or_walk (struct PlayerObj *arg0);
extern void player_zero_attack_finish (struct PlayerObj *arg0);
extern void player_zero_hyouretsuzan (struct PlayerObj *arg0);
extern void player_zero_ryuenjin (struct PlayerObj *arg0);
extern void player_zero_ryuenjin_spawn_flame (struct PlayerObj *arg0);
extern void func_8003B3DC (struct RideArmorObj *arg0);
extern void func_8003C6EC (struct RideArmorObj *arg0, u8 arg1);
extern void func_8003C8F4 (struct RideArmorObj *arg0);
extern void func_8003CB08 (struct RideArmorObj *arg0);
extern void func_8003CCBC (struct RideArmorObj *arg0);
extern void func_8003CD38 (struct RideArmorObj *arg0);
extern void func_8003DC44 (struct BaseObj *arg0, s8 arg1);
extern void heavy_mech_face_player (struct AnimatedObj *arg0);
extern s32 func_8003DC50 (struct RideArmorObj *arg0);
extern s32 ground_hunter_check_wall (struct WeaponObj *arg0);
extern s32 double_cyclone_check_expired (struct WeaponObj *arg0);
extern s32 double_cyclone_charged_check_expired (struct WeaponObj *arg0);
extern void func_8003F648 (struct RideArmorObj *arg0);
extern void background_dragon_update (struct MainObj *arg0);
extern void background_dragon_noop (struct MainObj *arg0);
extern void armored_walker_update (struct MainObj *arg0);
extern void item_carrier_drop_landed (struct MainObj *arg0);
extern void spike_marl_resume_step (struct MainObj *arg0);
extern void spike_marl_noop (struct MainObj *arg0);
extern void robot_bee_resume_step (struct MainObj *arg0);
extern void bulldozer_resume_step (struct MainObj *arg0);
extern void ambush_gunner_resume_step (struct MainObj *arg0);
extern void unused_main_09_update (struct MainObj *arg0);
extern void dragonfly_update (struct MainObj *arg0);
extern void dragonfly_init (struct MainObj *arg0);
extern void dragonfly_run (struct MainObj *arg0);
extern void dragonfly_resume_step (struct MainObj *arg0);
extern void dragonfly_wait (struct MainObj *arg0);
extern void heavy_mech_resume_step (struct MainObj *arg0);
extern void bee_hive_explode_done (void);
extern void slope_skier_slide_idle (void);
extern void ice_wall_idle (struct MainObj *arg0);
extern void ice_wall_break_idle (struct BaseObj *arg0);
extern void spawner_pod_idle (struct MainObj *arg0);
extern void spawner_pod_step_4 (struct MainObj *arg0);
extern void pod_spawner_idle (struct MainObj *arg0);
extern void pod_spawner_wait (struct MainObj *arg0);
extern void thorn_trap_idle (struct MainObj *arg0);
extern void data_hopper_idle (struct MainObj *arg0);
extern void train_boss_fight_idle (void);
extern void train_boss_turret_start_idle (struct MainObj *arg0);
extern void train_soldier_idle (struct MainObj *arg0);
extern void train_crate_idle (struct MainObj *arg0);
extern void wave_rider_idle (struct MainObj *arg0);
extern void slash_beast_update (struct MainObj *arg0);
extern void slash_beast_start_pattern (struct MainObj *arg0);
extern void slash_beast_intro (struct MainObj *arg0);
extern void frost_walrus_reset (struct MainObj *arg0);
extern void frost_walrus_blizzard_idle (struct MainObj *arg0);
extern void flame_jet_idle (struct MainObj *arg0);
extern void flame_jet_extinguished_idle (void);
extern void magma_dragoon_hold (struct MainObj *arg0);
extern void sigma_idle (struct MainObj *arg0);
extern void drone_pod_resume_step (struct MainObj *arg0);
extern void ride_armor_pilot_stub (struct MainObj *arg0, s32 arg1, s32 arg2);
extern void ride_armor_pilot_despawn_idle (void);
extern void ride_armor_pilot_despawn_idle2 (void);
extern void unused_ride_armor_despawn_idle (void);
extern void unused_ride_armor_despawn_idle2 (void);
extern void sigma_final_idle (struct MainObj *arg0);
extern void general_intro (struct MainObj *arg0);
extern void general_update (struct MainObj *arg0);
extern void spike_crawler_update (struct MainObj *arg0);
extern void lemon_update (struct WeaponObj *arg0);
extern void charge_shot_update (struct WeaponObj *arg0);
extern void stock_shot_update (struct WeaponObj *arg0);
extern void plasma_shot_update (struct WeaponObj *arg0);
extern void lightning_web_buzz_sound (struct WeaponObj *arg0, u8 *arg1);
extern void rising_fire_draw (struct WeaponObj *arg0);
extern void ground_hunter_start_rise (struct WeaponObj *arg0);
extern void ride_chaser_shot_update (struct WeaponObj *arg0);
extern void ride_chaser_ram_update (struct WeaponObj *arg0);
extern void ice_block_hitbox_update (struct WeaponObj *arg0);
extern void ride_armor_shot_update (struct WeaponObj *arg0);
extern void enemy_ride_armor_shot_update (struct ShotObj *arg0);
extern void ride_armor_missile_update (struct WeaponObj *arg0);
extern void ride_armor_punch_update (struct WeaponObj *arg0);
extern void dragon_shot_update (struct ShotObj *arg0);
extern void drill_copter_shot_update (struct ShotObj *arg0);
extern void gunner_shot_unused (struct ShotObj *arg0);
extern void gunner_shot_update (struct ShotObj *arg0);
extern void eregion_fireball_update (struct ShotObj *arg0);
extern void eregion_wing_slash_update (struct ShotObj *arg0);
extern void mech_boulder_update (struct ShotObj *arg0);
extern void wall_crawler_shot_update (struct ShotObj *arg0);
extern void wall_crawler_shot_idle (struct ShotObj *arg0);
extern void dropped_bomb_update (struct ShotObj *arg0);
extern void dropped_bomb_idle (struct ShotObj *arg0);
extern void shell_crawler_shot_update (struct ShotObj *arg0);
extern void trident_shot_update (struct ShotObj *arg0);
extern void dragon_spread_shot_update (struct ShotObj *arg0);
extern void dragon_spread_shot_idle (struct ShotObj *arg);
extern void enemy_bullet_update (struct ShotObj *arg0);
extern void ice_core_shot_update (struct ShotObj *arg0);
extern void jet_drone_bullet_update (struct ShotObj *arg0);
extern void dash_gunner_shot_update (struct ShotObj *arg0);
extern void turret_laser_update (struct ShotObj *arg0);
extern void turret_laser_idle (struct ShotObj *arg);
extern void linked_spark_update (struct ShotObj *arg0);
extern void depth_charge_update (struct ShotObj *arg0);
extern void depth_charge_idle (struct ShotObj *arg0);
extern void aimed_bullet_update (struct ShotObj *arg0);
extern void trooper_bomb_update (struct ShotObj *arg0);
extern void cannon_blast_update (struct ShotObj *arg0);
extern void cannon_blast_idle (struct ShotObj *arg0);
extern void cannon_shell_update (struct ShotObj *arg0);
extern void cannon_shell_idle (struct ShotObj *arg0);
extern void web_shot_update (struct ShotObj *arg0);
extern void web_thread_update (struct ShotObj *arg0);
extern void train_boss_shot_update (struct ShotObj *arg0);
extern void grenade_update (struct ShotObj *arg0);
extern void grenade_idle (struct ShotObj *arg0);
extern void sentry_shot_update (struct ShotObj *arg0);
extern void sentry_shot_idle (struct ShotObj *arg0);
extern void jump_shooter_shot_update (struct ShotObj *arg0);
extern void melee_hitbox_update (struct ShotObj *arg0);
extern void cannon_missile_update (struct ShotObj *arg0);
extern void cannon_missile_idle (struct ShotObj *arg0);
extern void cannon_shot_update (struct ShotObj *arg0);
extern void cannon_shot_idle (struct ShotObj *arg0);
extern void slash_beast_crescent_update (struct ShotObj *arg0);
extern void flame_pillar_update (struct ShotObj *arg0);
extern void falling_rock_update (struct ShotObj *arg0);
extern void ray_trap_update (struct ShotObj *arg0);
extern void walrus_ice_update (struct ShotObj *arg0);
extern void drone_beam_update (struct ShotObj *arg0);
extern void drone_beam_idle (struct ShotObj *arg0);
extern void owl_feather_update (struct ShotObj *arg0);
extern void owl_feather_idle (struct ShotObj *arg0);
extern void owl_cyclone_update (struct ShotObj *arg0);
extern void owl_cyclone_idle (struct ShotObj *arg0);
extern void mushroom_shot_update (struct ShotObj *arg0);
extern void hatch_blast_update (struct ShotObj *arg0);
extern void magma_fire_idle (struct ShotObj *arg0);
extern void magma_fire_update (struct ShotObj *arg0);
extern void peacock_missile_update (struct ShotObj *arg0);
extern void func_800A666C (struct ShotObj *arg0, s32 arg1, s32 arg2);
extern void gunship_shot_update (struct ShotObj *arg0);
extern void gunship_shot_idle (struct ShotObj *arg0);
extern void iris_shot_update (struct ShotObj *arg0);
extern void colonel_shot_update (struct ShotObj *arg0);
extern void sigma_bolt_idle (struct ShotObj *arg0);
extern void sigma_shot_update (struct ShotObj *arg0);
extern void double_ball_update (struct ShotObj *arg0);
extern void double_aerial_update (struct ShotObj *arg0);
extern void double_bouncer_update (struct ShotObj *arg0);
extern void double_mine_update (struct ShotObj *arg0);
extern void double_mine_shot_update (struct ShotObj *arg0);
extern void sigma_head_idle (struct ShotObj *arg0);
extern void sigma_head_update (struct ShotObj *arg0);
extern void sigma_final_shot_idle (struct ShotObj *arg0);
extern void sigma_final_shot_update (struct ShotObj *arg0);
extern void general_shot_update (struct ShotObj *arg0);
extern void sigma_spit_idle (struct ShotObj *arg0);
extern void sigma_spit_update (struct ShotObj *arg0);
extern void sigma_beam_hitbox_update (struct ShotObj *arg0);
extern void func_800AE714 (struct BazObj *arg0, struct PlayerObj *arg1);
extern void func_800AE790 (struct BazObj *arg0, struct PlayerObj *arg1);
extern void func_800AE7DC (struct UnkObj *arg0);
extern void func_800AE848 (struct UnkObj *arg0, struct PlayerObj *player);
extern void wall_slide_dust_update (struct VisualObj *arg0);
extern void wall_slide_dust_init (struct VisualObj *arg0, struct PlayerObj *arg1);
extern void wall_slide_dust_main (struct VisualObj *arg0, struct PlayerObj *arg1);
extern void wall_slide_dust_fade (struct VisualObj *arg0, struct PlayerObj *arg1);
extern void wall_slide_dust_attach (struct VisualObj *arg0, struct PlayerObj *arg1);
extern void dash_dust_attach (struct VisualObj *arg0, struct PlayerObj *arg1);
extern void charge_muzzle_flash_update (struct VisualObj *arg0);
extern void charge_muzzle_flash_init (struct VisualObj *arg0);
extern void charge_muzzle_flash_main (struct VisualObj *arg0);
extern void charge_muzzle_flash_spawn_shot (struct VisualObj *arg0);
extern void charge_muzzle_flash_fade (struct VisualObj *arg0);
extern void charge_muzzle_flash_follow (struct VisualObj *arg0);
extern void water_wake_update (struct VisualObj *arg0);
extern void water_wake_init (struct VisualObj *arg0, struct VisualObj *arg1);
extern void water_wake_main (struct VisualObj *arg0, struct PlayerObj *arg1);
extern void water_wake_hidden (struct VisualObj *arg0, struct PlayerObj *arg1);
extern void water_wake_idle (struct VisualObj *arg0, struct PlayerObj *arg1);
extern void water_wake_moving (struct VisualObj *arg0, struct PlayerObj *arg1);
extern void spawn_explosion (struct BaseObj *arg0);
extern void spawn_explosion_variant (struct BaseObj *arg0, s8 arg1);
extern void blast_update (struct VisualObj *arg0);
extern void blast_animate (struct VisualObj *arg0);
extern void ice_shard_update (struct VisualObj *arg0);
extern void ice_shard_idle (struct VisualObj *arg0);
extern void dust_puff_update (struct VisualObj *arg0);
extern void dragon_fx_update (struct VisualObj *arg0);
extern void dragon_fx_flash_init (struct VisualObj *arg0);
extern void dragon_fx_animate (struct VisualObj *arg0);
extern void dragon_fx_despawn (struct VisualObj *arg0);
extern void charge_ring_update (struct VisualObj *arg0);
extern void charge_ring_init (struct VisualObj *arg0);
extern void charge_ring_despawn (struct VisualObj *arg0);
extern void ride_dust_update (struct VisualObj *arg0);
extern void ride_dust_init (struct VisualObj *arg0);
extern void ride_dust_main (struct VisualObj *arg0);
extern void ride_dust_despawn (struct VisualObj *arg0);
extern void ride_chaser_jet_update (struct VisualObj *arg0);
extern void ride_chaser_jet_init (struct VisualObj *arg0);
extern void ride_chaser_jet_despawn (struct VisualObj *arg0);
extern void lift_effect_update (struct VisualObj *arg0);
extern void lift_effect_init (struct VisualObj *arg0);
extern void lift_effect_main (struct VisualObj *arg0);
extern void lift_effect_despawn (struct VisualObj *arg0);
extern void ride_chaser_flash_update (struct VisualObj *arg0);
extern void ride_chaser_flash_init (struct VisualObj *arg0);
extern void ride_chaser_flash_main (struct VisualObj *arg0);
extern void ride_chaser_flash_despawn (struct VisualObj *arg0);
extern void enemy_charge_glow_update (struct VisualObj *arg0);
extern void enemy_charge_glow_despawn (struct VisualObj *arg0);
extern void web_piece_update (struct VisualObj *arg0);
extern void web_piece_main (struct VisualObj *arg0);
extern void web_piece_hang (struct VisualObj *arg0);
extern void web_piece_fall (struct VisualObj *arg0);
extern void aiming_laser_scope_update (struct VisualObj *arg0);
extern void double_cyclone_charged_fan_draw (struct VisualObj *arg0);
extern void weapon_overlay_update (struct VisualObj *arg0);
extern void weapon_gfx_preload_update (struct VisualObj *arg0);
extern void hover_jet_update (struct VisualObj *arg0);
extern void stock_charge_meter_update (struct MiscObj *arg0);
extern void web_flash_update (struct VisualObj *arg0);
extern void web_flash_init (struct VisualObj *arg0);
extern void web_flash_main (struct VisualObj *arg0);
extern void wave_rider_jet_init (struct VisualObj *arg0);
extern void wave_rider_jet_main (struct VisualObj *arg0);
extern void wave_rider_jet_despawn (struct VisualObj *arg0);
extern void wave_rider_jet_update (struct VisualObj *arg0);
extern void missile_smoke_update (struct VisualObj *arg0);
extern void missile_smoke_init (struct VisualObj *arg0);
extern void missile_smoke_main (struct VisualObj *arg0);
extern void missile_smoke_despawn (struct VisualObj *arg0);
extern void jet_stingray_fx_init (struct VisualObj *arg0);
extern void jet_stingray_fx_vortex (struct VisualObj *arg0);
extern void jet_stingray_fx_splash (struct VisualObj *arg0);
extern void jet_stingray_fx_oneshot (struct VisualObj *arg0);
extern void jet_stingray_fx_main (struct VisualObj *arg0);
extern void jet_stingray_fx_despawn (struct VisualObj *arg0);
extern void jet_stingray_fx_update (struct VisualObj *arg0);
extern void frost_walrus_fx_update (struct VisualObj *arg0);
extern void flame_jet_fx_update (struct VisualObj *arg0);
extern void storm_owl_fx_update (struct VisualObj *arg0);
extern void peacock_target_update (struct VisualObj *arg0);
extern void peacock_target_main (struct VisualObj *arg0);
extern void colonel_fx_update (struct VisualObj *arg0);
extern void colonel_fx_main (struct VisualObj *arg0);
extern void colonel_fx_beam_in (struct VisualObj *arg0);
extern void colonel_fx_flash (struct VisualObj *arg0);
extern void colonel_fx_slash_animate (struct VisualObj *arg0);
extern void colonel_fx_ground (struct VisualObj *arg0);
extern void colonel_fx_ground_start (struct VisualObj *arg0);
extern void colonel_fx_ground_animate (struct VisualObj *arg0);
extern void gunship_exhaust_update (struct VisualObj *arg0);
extern void gunship_exhaust_delay (struct VisualObj *arg0);
extern void gunship_exhaust_despawn (struct VisualObj *arg0);
extern void sigma_fx_glow (struct VisualObj *arg0);
extern void sigma_cloak_piece_wait (struct VisualObj *arg0);
extern void sigma_cloak_piece_blink (struct VisualObj *arg0);
extern void sigma_fx_cloak_piece (struct VisualObj *arg0);
extern void sigma_fx_hit_glow (struct VisualObj *arg0);
extern void sigma_fx_run (struct VisualObj *arg0);
extern void sigma_fx_despawn (struct VisualObj *arg0);
extern void sigma_fx_update (struct VisualObj *arg0);
extern void split_mushroom_fx_update (struct VisualObj *arg0);
extern void split_mushroom_fx_main (struct VisualObj *arg0);
extern void split_mushroom_fx_despawn (struct VisualObj *arg0);
extern void camera_trigger_update (struct EffectObj *arg0);
extern void camera_trigger_init (struct EffectObj *arg0);
extern void tile_animator_update (struct EffectObj *arg0);
extern void tile_animator_step (struct EffectObj *arg0, s32 arg1, s32 arg2);
extern void color_filter_init (struct EffectObj *arg0);
extern void color_filter_step (struct EffectObj *arg0);
extern void copy_animated_palette (struct EffectObj *arg0);
extern void palette_animator_update (struct EffectObj *arg0);
extern void palette_animator_step (struct EffectObj *arg0);
extern void stage_music_update (struct EffectObj *arg0);
extern void checkpoint_trigger_update (struct EffectObj *arg0);
extern void checkpoint_trigger_init (struct EffectObj *arg0);
extern void checkpoint_trigger_wait (struct EffectObj *arg0);
extern void search_light_maker_update (struct EffectObj *arg0);
extern void search_light_maker_init (struct EffectObj *arg0);
extern void search_light_maker_main (struct EffectObj *arg0);
extern void search_light_maker_idle (struct EffectObj *arg0);
extern void search_light_maker_spawn_scrolled (struct EffectObj *arg0);
extern void bg_zone_controller_update (struct EffectObj *arg0);
extern void bg_zone_controller_idle (struct EffectObj *arg0);
extern void bg_wind_update (struct EffectObj *arg0);
extern void null_effect_update (struct EffectObj *arg0);
extern void enemy_spawner_update (struct EffectObj *arg0);
extern void edge_spawner_update (struct EffectObj *arg0);
extern void item_scatter_update (struct EffectObj *arg0);
extern void bg_zone_controller_b_update (struct EffectObj *arg0);
extern void bg_zone_controller_b_idle (struct EffectObj *arg0);
extern void autoscroll_segment_update (struct EffectObj *arg0);
extern void freeze_blast_update (struct EffectObj *arg0);
extern void world_flip_update (struct EffectObj *arg0);
extern void bg_zone_controller_c_update (struct EffectObj *arg0);
extern void bg_zone_controller_c_idle (struct EffectObj *arg0);
extern void bg_zone_controller_d_update (struct EffectObj *arg0);
extern void bg_zone_controller_d_idle (struct EffectObj *arg0);
extern void crumble_sequencer_update (struct EffectObj *arg0);
extern void bg_zone_controller_e_update (struct EffectObj *arg0);
extern void bg_zone_controller_e_idle (struct EffectObj *arg0);
extern void tile_flicker_update (struct EffectObj *arg0);
extern void boss_warning_update (struct EffectObj *arg0);
extern void bg_zone_controller_f_update (struct EffectObj *arg0);
extern void bg_zone_controller_f_idle (struct EffectObj *arg0);
extern void boss_death_fx_update (struct EffectObj *arg0);
extern void teleport_intro_init (struct EffectObj *arg0);
extern void teleport_intro_spawn_quads (struct EffectObj *arg0);
extern void fortress_collapse_update (struct EffectObj *arg0);
extern void tile_anim_trigger_update (struct EffectObj *arg0);
extern void qux_spawner_update (struct EffectObj *arg0);
extern void floor_trap_wait (struct EffectObj *arg0);
extern void floor_trap_update (struct EffectObj *arg0);
extern void proximity_door_update (struct EffectObj *arg0);
extern void rock_dropper_update (struct EffectObj *arg0);
extern void rock_dropper_idle (struct EffectObj *arg0);
extern void rock_drop_sequence_update (struct EffectObj *arg0);
extern void rock_drop_sequence_idle (struct EffectObj *arg0);
extern void palette_pulse_update (struct EffectObj *arg0);
extern void stage_exit_fade_update (struct EffectObj *arg0);
extern void alarm_flash_update (struct EffectObj *arg0);
extern void cyberspace_trial_update (struct EffectObj *arg0);
extern void tile_strip_anim_update (struct EffectObj *arg0);
extern void tile_loop_anim_update (struct EffectObj *arg0);
extern void tile_blink_anim_update (struct EffectObj *arg0);
extern void sigma_sequencer_fx_update (struct EffectObj *arg0);
extern void sigma_collapse_update (struct EffectObj *arg0);
extern void stage_dialogue_trigger_update (struct EffectObj *arg0);
extern void breakable_wall_update (struct ItemObj *arg0);
extern void stage_block_update (struct ItemObj *arg0);
extern void pickup_update (struct ItemObj *arg0);
extern void falling_pillar_update (struct ItemObj *arg0);
extern void destructible_core_update (struct ItemObj *arg0);
extern void moving_lift_update (struct ItemObj *arg0);
extern void gate_core_update (struct ItemObj *arg0);
extern void rising_platform_update (struct ItemObj *arg0);
extern void boss_door_update (struct ItemObj *arg0);
extern void moving_block_update (struct ItemObj *arg0);
extern void spark_machine_update (struct ItemObj *arg0);
extern void teleporter_update (struct ItemObj *arg0);
extern void crusher_wall_idle (struct ItemObj *arg0);
extern void trap_floor_update (struct ItemObj *arg0);
extern void big_elevator_update (struct ItemObj *arg0);
extern void rising_slab_update (struct ItemObj *arg0);
extern void crumble_trigger_update (struct ItemObj *arg0);
extern void drop_pillar_update (struct ItemObj *arg0);
extern void data_capsule_idle (struct ItemObj *arg0);
extern void gravity_switch_update (struct ItemObj *arg0);
extern void hopper_switch_update (struct ItemObj *arg0);
extern void layout_gate_update (struct ItemObj *arg0);
extern void laser_target_update (struct ItemObj *arg0);
extern void breakable_panel_update (struct ItemObj *arg0);
extern void light_capsule_idle (struct ItemObj *arg0);
extern void boss_teleporter_update (struct ItemObj *arg0);
extern void briefing_character_init (struct MiscObj *arg0);
extern void briefing_character_animate (struct MiscObj *arg0);
extern void blink_marker_update (struct MiscObj *arg0);
extern void ready_text_init (struct MiscObj *arg0);
extern void ready_text_main (struct MiscObj *arg0);
extern void ready_text_word (struct MiscObj *arg0);
extern void ready_text_appear (struct MiscObj *arg0);
extern void ready_text_bounce (struct MiscObj *arg0);
extern void ready_text_leave (struct MiscObj *arg0);
extern void ready_text_blink (struct MiscObj *arg0);
extern void ready_text_show (struct MiscObj *arg0);
extern void ready_text_load_palette (s32 arg0, s32 arg1);
extern void ready_text_despawn (struct MiscObj *arg0);
extern void title_init (struct MiscObj *arg0);
extern void title_draw (struct MiscObj *arg0);
extern void title_despawn (struct MiscObj *arg0);
extern void center_sprite_update (struct MiscObj *arg0);
extern void scroll_prop_update (struct MiscObj *arg0);
extern void dialogue_ui_update (struct MiscObj *arg0);
extern void explosion_puff_update (struct MiscObj *arg0);
extern void explosion_puff_init (struct MiscObj *arg0);
extern void explosion_puff_animate (struct MiscObj *arg0);
extern void enemy_hatch_update (struct MiscObj *arg0);
extern void enemy_hatch_main (struct MiscObj *arg0);
extern void enemy_hatch_wait (struct MiscObj *arg0);
extern void enemy_hatch_release (struct MiscObj *arg0);
extern void enemy_hatch_close (struct MiscObj *arg0);
extern void slash_beast_afterimage_update (struct MiscObj *arg0);
extern void owner_aura_update (struct MiscObj *arg0);
extern void select_char_init (struct MiscObj *arg0);
extern void select_char_portrait_slide_in (struct MiscObj *arg0);
extern void select_char_portrait_wait_select (struct MiscObj *arg0);
extern void select_char_portrait_slide_out (struct MiscObj *arg0);
extern void select_char_portrait_bounce (struct MiscObj *arg0);
extern void select_char_portrait (struct MiscObj *arg0);
extern void select_char_scroll_text_init (struct MiscObj *arg0);
extern void select_char_scroll_text_move (struct MiscObj *arg0);
extern void select_char_scroll_text (struct MiscObj *arg0);
extern void select_char_selector_move (struct MiscObj *arg0);
extern void select_char_selector_animate (struct MiscObj *arg0);
extern void select_char_selector (struct MiscObj *arg0);
extern void select_char_character_idle (struct MiscObj *arg0);
extern void select_char_character_shoot (struct MiscObj *arg0);
extern void select_char_character (struct MiscObj *arg0);
extern void select_char_charged_shot_fly (struct MiscObj *arg0);
extern void select_char_shot_burst (struct MiscObj *arg0);
extern void select_char_character_exit (struct MiscObj *arg0);
extern void select_char_main (struct MiscObj *arg0);
extern void select_char_despawn (struct MiscObj *arg0);
extern void title_logo_init (struct MiscObj *arg0);
extern void title_logo_star_delay (struct MiscObj *arg0);
extern void title_logo_star_fly (struct MiscObj *arg0);
extern void title_logo_star_hold (struct MiscObj *arg0);
extern void title_logo_trail_fade (struct MiscObj *arg0);
extern void title_logo_fade_start (struct MiscObj *arg0);
extern void title_logo_fade_palette (struct MiscObj *arg0);
extern void title_logo_sparkle (struct MiscObj *arg0);
extern void stage_cutscene_idle (struct UnkObj *arg0);
extern void scripted_slider_idle (void);
extern void sigma_final_fx_gust (struct MiscObj *arg0);
extern void menu_text_init_label (struct UnkObj *arg0);
extern void menu_text_init_cursor (struct UnkObj *arg0);
extern void menu_text_init (struct UnkObj *arg0);
extern void menu_text_highlight (struct UnkObj *arg0);
extern void menu_text_cursor (struct UnkObj *arg0);
extern void menu_text_update (struct UnkObj *arg0);
extern void menu_label_init (struct UnkObj *arg0);
extern void menu_label_highlight (struct UnkObj *arg0);
extern void menu_label_update (struct UnkObj *arg0);
extern void search_light_init (struct QuadObj *arg0);
extern void search_light_move (struct Unk22 *arg0);
extern void stage_select_panel_update (struct QuadObj *arg0);
extern void stage_select_panel_idle (struct QuadObj *arg0);
extern void stage_select_flyout_update (struct QuadObj *arg0);
extern void boss_warning_quad_despawn (struct QuadObj *arg0);
extern void boss_warning_quad_update (struct QuadObj *arg0);
extern void boss_death_shard_update (struct QuadObj *arg0);
extern void web_piece_quad_update (struct QuadObj *arg0);
extern void web_piece_quad_despawn (struct QuadObj *arg0);
extern void light_ray_despawn (struct QuadObj *arg0);
extern void light_ray_update (struct QuadObj *arg0);
extern void ready_line_update (struct QuadObj *arg0);
extern void ready_line_init (struct QuadObj *arg0);
extern void ready_line_main (struct QuadObj *arg0);
extern void ready_line_sweep (struct QuadObj *arg0);
extern void ready_line_shutter (struct QuadObj *arg0);
extern void ready_line_streak (struct QuadObj *arg0);
extern void ready_line_move (struct QuadObj *arg0);
extern void ready_line_converge_vertex (struct QuadObj *arg0, arg_u8 arg1, s32 arg2, const s16 *target);
extern void ready_line_despawn (struct QuadObj *arg0);
extern void ready_line_nop (void);
extern void flash_band_init (struct QuadObj *arg0);
extern void flash_band_despawn (struct QuadObj *arg0);
extern void flash_band_update (struct QuadObj *arg0);
extern void aiming_laser_beam_update (struct QuadObj *arg0);
extern void aiming_laser_beam_init (struct QuadObj *arg0, struct PlayerObj *arg1, struct PlayerObj *arg2);
extern void aiming_laser_beam_main (struct QuadObj *arg0, struct PlayerObj *arg1, struct PlayerObj *arg2);
extern void aiming_laser_charged_beam_update (struct QuadObj *arg0);
extern void title_quad_init (struct QuadObj *entity);
extern void title_quad_delay (struct QuadObj *arg0);
extern void title_quad_morph (struct QuadObj *arg0);
extern void title_quad_despawn (struct QuadObj *arg0);
extern void title_facet_init (struct QuadObj *arg0);
extern void title_facet_follow (struct QuadObj *arg0);
extern void title_facet_finish (struct QuadObj *arg0);
extern void title_facet_despawn (struct QuadObj *arg0);
extern void title_facet_update (struct QuadObj *arg0);
extern void quad_null_update (struct QuadObj *arg0);
extern void colonel_beam_update (struct QuadObj *arg0);
extern void colonel_beam_main (struct QuadObj *arg0);
extern void colonel_beam_despawn (struct QuadObj *arg0);
extern void colonel_beam_drop (struct QuadObj *arg0);
extern void colonel_beam_wait (struct QuadObj *arg0);
extern void colonel_beam_place (struct QuadObj *arg0, u8 arg1);
extern void sigma_beam_init (struct QuadObj *arg0);
extern void sigma_beam_extend (struct QuadObj *arg0);
extern void sigma_beam_sweep (struct QuadObj *arg0);
extern void sigma_beam_fade (struct QuadObj *arg0);
extern void sigma_beam_main (struct QuadObj *arg0);
extern void sigma_beam_despawn (struct QuadObj *arg0);
extern void sigma_beam_update (struct QuadObj *arg0);
extern void sigma_laser_wait (struct QuadObj *arg0);
extern void sigma_laser_flash (struct QuadObj *arg0);
extern void sigma_laser_main (struct QuadObj *arg0);
extern void sigma_laser_cancel_wait (struct QuadObj *arg0);
extern void sigma_laser_cancel (struct QuadObj *arg0);
extern void sigma_laser_despawn (struct QuadObj *arg0);
extern void sigma_laser_update (struct QuadObj *arg0);
extern void train_scroll_update (struct LayerObj *arg0);
extern void train_scroll_main (struct LayerObj *arg0);
extern void train_scroll_despawn (struct LayerObj *arg0);
extern void train_scroll_section_0 (struct LayerObj *arg0);
extern void train_scroll_section_0_wait (struct LayerObj *arg0);
extern void train_scroll_section_0_skip (struct LayerObj *arg0);
extern void train_scroll_section_1 (struct LayerObj *arg0);
extern void train_scroll_section_1_lock (struct LayerObj *arg0);
extern void train_scroll_section_1_event (struct LayerObj *arg0);
extern void train_scroll_section_2 (struct LayerObj *arg0);
extern void train_scroll_section_2_lock (struct LayerObj *arg0);
extern void train_scroll_section_2_event (struct LayerObj *arg0);
extern void train_scroll_section_3 (struct LayerObj *arg0);
extern void train_scroll_section_3_lock (struct LayerObj *arg0);
extern void train_scroll_section_3_event (struct LayerObj *arg0);
extern void train_scroll_section_4 (struct LayerObj *arg0);
extern void train_scroll_section_4_lock (struct LayerObj *arg0);
extern void train_scroll_section_4_event (struct LayerObj *arg0);
extern void train_scroll_section_5 (struct LayerObj *arg0);
extern void train_scroll_spawn_trooper (struct LayerObj *arg0);
extern void train_scroll_spawn_crusher (struct LayerObj *arg0);
extern void train_scroll_open_tiles (struct LayerObj *arg0);
extern void train_scroll_shake (struct LayerObj *arg0);
extern void jungle_parallax_update (struct LayerObj *arg0);
extern void jungle_parallax_init (struct LayerObj *arg0);
extern void jungle_parallax_main (struct LayerObj *arg0);
extern void jungle_parallax_section_0 (struct LayerObj *arg0);
extern void jungle_parallax_section_0_setup (struct LayerObj *arg0);
extern void jungle_parallax_section_1 (struct LayerObj *arg0);
extern void jungle_parallax_section_1_setup (struct LayerObj *arg0);
extern void jungle_parallax_section_1_done (struct LayerObj *arg0);
extern void jungle_parallax_section_2 (struct LayerObj *arg0);
extern void jungle_parallax_section_2_setup (struct LayerObj *arg0);
extern void jungle_parallax_idle (struct LayerObj *arg0);
extern void jungle_parallax_update_section (struct LayerObj *arg0);
extern void train_tunnel_update (struct LayerObj *arg0);
extern void train_tunnel_despawn (struct LayerObj *arg0);
extern void train_tunnel_section_0 (struct LayerObj *arg0);
extern void train_tunnel_section_0_wait (struct LayerObj *arg0);
extern void train_tunnel_section_0_skip (struct LayerObj *arg0);
extern void train_tunnel_section_1 (struct LayerObj *arg0);
extern void train_tunnel_wait_stop_point (struct LayerObj *arg0);
extern void train_tunnel_start_braking (struct LayerObj *arg0);
extern void train_tunnel_brake (struct LayerObj *arg0);
extern void train_tunnel_section_2 (struct LayerObj *arg0);
extern void train_tunnel_start_departure (struct LayerObj *arg0);
extern void train_tunnel_accelerate (struct LayerObj *arg0);
extern void train_tunnel_section_3 (struct LayerObj *arg0);
extern void train_tunnel_section_3_wait (struct LayerObj *arg0);
extern void train_tunnel_section_3_skip (struct LayerObj *arg0);
extern void train_tunnel_section_4 (struct LayerObj *arg0);
extern void train_tunnel_section_4_wait (struct LayerObj *arg0);
extern void train_tunnel_section_4_skip (struct LayerObj *arg0);
extern void train_tunnel_idle (struct LayerObj *arg0);
extern void volcano_camera_update (struct LayerObj *arg0);
extern void volcano_camera_init (struct LayerObj *arg0);
extern void volcano_camera_main (struct LayerObj *arg0);
extern void volcano_camera_despawn (struct LayerObj *arg0);
extern void volcano_camera_section_0 (struct LayerObj *arg0);
extern void volcano_camera_section_0_wait (struct LayerObj *arg0);
extern void volcano_camera_section_0_done (struct LayerObj *arg0);
extern void volcano_camera_section_1 (struct LayerObj *arg0);
extern void volcano_camera_section_1_wait (struct LayerObj *arg0);
extern void volcano_camera_section_1_done (struct LayerObj *arg0);
extern void volcano_camera_idle (struct LayerObj *arg0);
extern void airship_bob_update (struct LayerObj *arg0);
extern void airship_bob_despawn (struct LayerObj *arg0);
extern void airship_bob_section_0 (struct LayerObj *arg0);
extern void airship_bob_section_0_wait (struct LayerObj *arg0);
extern void airship_bob_section_0_done (struct LayerObj *arg0);
extern void airship_bob_section_1 (struct LayerObj *arg0);
extern void airship_bob_section_1_wait (struct LayerObj *arg0);
extern void airship_bob_section_1_done (struct LayerObj *arg0);
extern void airship_bob_section_2 (struct LayerObj *arg0);
extern void airship_bob_section_2_wait (struct LayerObj *arg0);
extern void airship_bob_section_2_done (struct LayerObj *arg0);
extern void airship_bob_idle (struct LayerObj *arg0);
extern void final_weapon_bg_cycle_update (struct LayerObj *arg0);
extern void final_weapon_bg_cycle_init (struct LayerObj *arg0);
extern void space_port_parallax_update (struct LayerObj *arg0);
extern void space_port_parallax_init (struct LayerObj *arg0);
extern void space_port_parallax_despawn (struct LayerObj *arg0);
extern void tile_effect_nop (void);
extern void load_palette (void);
extern void load_vram_rect_ptrs (void);
extern void reset_entity (struct PlayerObj *arg0);
extern void reset_main_and_shots (void);
extern void update_effect_objects (void);
extern void update_item_objects (void);
extern void update_layer_objects (void);
extern void update_main_objects (void);
extern void update_misc_objects (void);
extern void update_quad_objects (void);
extern void update_shot_objects (void);
extern void update_unk_objects (void);
extern void update_visual_objects (void);
extern void update_weapon_objects (void);

#endif
