name: Build PSX version

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '*.md'
      - '**/*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.job }}-${{ github.event_name }}-${{ github.number }}
  cancel-in-progress: false

jobs:
  build-and-test:
    strategy:
      matrix:
        version: ["us"]
        include:
          - dependency: us
            version: us
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ matrix.version }}
    steps:
      - name: Install requirements
        run: sudo apt-get install gcc-mipsel-linux-gnu bchunk ninja-build
      - name: Install python requirements
        run: pip3 install splat64==0.24.6 spimdisasm>=1.26.0 rabbitizer>=1.11.0 n64img==0.3.3 pygfxd crunch64 tabulate
      - name: Clone main repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: true
      - name: Build psximager
        run: |
          sudo apt-get install libcdio-dev libvcdinfo-dev libboost-all-dev
          cd tools/psximager
          ./bootstrap
          ./configure
          make
      - name: Lint
        run: sh format.sh && git diff --exit-code
      - name: Get dependencies
        uses: actions/checkout@v4
        with:
          repository: sozud/mmx4-deps
          ref: main
          token: ${{ secrets.MMX4_DEPS_TOKEN }}
          path: 'disks/dependencies'
      - name: Setting up dependencies
        working-directory: disks
        run: cat dependencies/* | tar -zxf -
      - name: Extract dependencies
        run: sh extract.sh
      - name: Get Compiler
        run: sh compiler.sh
      - name: Split game data
        run: splat split ./config/SLUS_005.61.splat.yaml
      - name: Build binaries
        run: sh build.sh
      - name: Get dependencies
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          repository: sozud/mmx4-info
          ref: main
          token: ${{ secrets.MMX4_INFO_TOKEN }}
          path: 'info'
      - name: Generate functions list
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: python3 ./tools/funcs_todo.py > info/functions.md
      - name: Commit all reports
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
            git config --global user.name 'GitHub Action'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add -A
            git commit -m 'Update reports' || true
            git push
        working-directory: info