name: Build PSX version

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '*.md'
      - '**/*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.job }}-${{ github.event_name }}-${{ github.number }}
  cancel-in-progress: false

jobs:
  build-and-test:
    strategy:
      matrix:
        version: ["us"]
        include:
          - dependency: us
            version: us
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ matrix.version }}
    steps:
      - name: Install requirements
        run: sudo apt-get install gcc-mipsel-linux-gnu bchunk
      - name: Install python requirements
        run: pip3 install splat64==0.24.6 spimdisasm>=1.26.0 rabbitizer>=1.11.0 n64img==0.3.3
      - name: Clone main repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: false
      - name: Get dependencies
        uses: actions/checkout@v4
        with:
          repository: sozud/mmx4-deps
          ref: main
          token: ${{ secrets.MMX4_DEPS_TOKEN }}
          path: 'disks/dependencies'
      - name: Setting up dependencies
        working-directory: disks
        run: cat dependencies/* | tar -zxf -
      - name: Extract dependencies
        run: sh extract.sh
      - name: Split game data
        run: sh split.sh
      - name: Build binaries
        run: sh build.sh
